const { PREFIX } = require(`${BASE_DIR}/config`);
const { InvalidParameterError } = require(`${BASE_DIR}/errors`);

module.exports = {
  name: "fofoca",
  description: "Faz fofoca aleatória sobre alguém",
  commands: ["fofoca", "fofoquinha"],
  usage: `${PREFIX}fofoca`,

  handle: async ({ sendText, getGroupMetadata, chatId, isGroup }) => {
    if (!isGroup) throw new InvalidParameterError("❗ Só funciona em grupos.");

    const groupMetadata = await getGroupMetadata(chatId);
    const participants = groupMetadata.participants.map(p => p.id.replace(/@.+/, ""));

    const escolhido = participants[Math.floor(Math.random() * participants.length)];

    const fofocas = [
      `👀 Tô sabendo que @${escolhido} anda mandando nudes escondido...`,
      `📢 @${escolhido} foi visto beijando o primo(a)!`,
      `😏 Dizem que @${escolhido} só toma banho de 3 em 3 dias...`,
      `🛑 Fofoca quente: @${escolhido} já levou chifre e não contou pra ninguém.`,
      `🔥 @${escolhido} foi pego cheirando pó no banheiro da firma!`,
      `💀 @${escolhido} traiu o namorado(a) com a melhor amiga!`,
      `🚨 @${escolhido} já foi preso por importunação sexual!`,
      `🤰 @${escolhido} já fez aborto escondido da família!`,
      `💸 @${escolhido} deve agiota e tá se escondendo!`,
      `👙 @${escolhido} vende pack do pé na internet!`,
      `🍆 @${escolhido} manda foto do pau pra desconhecidos!`,
      `📱 @${escolhido} tem perfil fake pra stalkear ex!`,
      `💔 @${escolhido} foi corno(a) 3 vezes e continua na relação!`,
      `🚿 @${escolhido} não lava a louça há 2 semanas!`,
      `🐀 @${escolhido} já comeu comida estragada pra não desperdiçar!`,
      `💋 @${escolhido} beijou o amigo(a) do(a) namorado(a)!`,
      `👂 @${escolhido} escuta conversa alheia no fone!`,
      `🤑 @${escolhido} já roubou dinheiro da mãe!`,
      `🍑 @${escolhido} já fez sexo anal no primeiro encontro!`,
      `🚫 @${escolhido} foi banido do Tinder por assédio!`,
      `🤥 @${escolhido} mente o salário pra impressionar!`,
      `🍺 @${escolhido} já mijou na calça bêbado!`,
      `👃 @${escolhido} não corta a unha do pé há meses!`,
      `💅 @${escolhido} usa esmalte vencido há 2 anos!`,
      `🤢 @${escolhido} já vomitou na cama e dormiu em cima!`,
      `📸 @${escolhido} tem fotos íntimas do(a) ex no celular!`,
      `💊 @${escolhido} toma remédio tarja preta escondido!`,
      `👵 @${escolhido} já deu em cima da avó do amigo!`,
      `🤫 @${escolhido} ronca mais alto que caminhão!`,
      `💩 @${escolhido} já cagou na rua e não limpou!`,
      `🍌 @${escolhido} já comeu comida do lixo!`,
      `👻 @${escolhido} já deu ghosting em 10 pessoas!`,
      `🦠 @${escolhido} não escova os dentes antes de dormir!`,
      `💰 @${escolhido} já vendeu coisa roubada!`,
      `🎭 @${escolhido} tem perfil fake de influencer!`,
      `🍆 @${escolhido} já tentou vender onlyfans e não vendeu nada!`,
      `🤮 @${escolhido} já reviveu relacionamento tóxico 5 vezes!`,
      `👃 @${escolhido} tem mau hálito crônico!`,
      `💸 @${escolhido} já pediu dinheiro emprestado e não pagou!`,
      `📉 @${escolhido} já foi demitido por incompetência!`,
      `🍷 @${escolhido} já bebeu vinho de garrafa de 5 reais!`,
      `🚬 @${escolhido} fuma bituca de cigarro achada no chão!`,
      `👖 @${escolhido} usa a mesma calça 1 semana seguida!`,
      `🛌 @${escolhido} não troca a roupa de cama há 2 meses!`,
      `🐛 @${escolhido} já comeu inseto sem querer e falou que gostou!`,
      `💍 @${escolhido} já pediu alguém em casamento e foi rejeitado!`,
      `👶 @${escolhido} já fingiu gravidez pra prender namorado!`,
      `📞 @${escolhido} liga pra ex toda vez que bebe!`,
      `🤰 @${escolhido} já fez teste de DNA escondido!`,
      `💔 @${escolhido} já terminou por mensagem de texto!`,
      `🍑 @${escolhido} já traiu com a irmã gêmea do parceiro!`,
      `🚓 @${escolhido} já fugiu da polícia correndo!`,
      `💸 @${escolhido} já apostou o dinheiro do aluguel!`,
      `🤥 @${escolhido} mente a altura no Tinder!`,
      `👃 @${escolhido} fuça o nariz e come a meleca!`,
      `🦶 @${escolhido} tem chulé que derruba mosca!`,
      `💦 @${escolhido} já molhou a cama depois de adulto!`,
      `📱 @${escolhido} hackeou as redes do ex!`,
      `👀 @${escolhido} espia os vizinhos pelados!`,
      `💊 @${escolhido} já vendeu receita médica falsa!`,
      `🍆 @${escolhido} já comprou pinto de borracha!`,
      `🤢 @${escolhido} não lava a toalha há 6 meses!`,
      `💅 @${escolhido} faz as unhas 1 vez por ano!`,
      `👃 @${escolhido} tem tampão de cera no ouvido!`,
      `🍌 @${escolhido} já comeu banana com maionese!`,
      `🚽 @${escolhido} não dá descarga quando faz xixi!`,
      `🐷 @${escolhido} ronca como porco na ceva!`,
      `💸 @${escolhido} já pegou empréstimo consignado!`,
      `🤫 @${escolhido} já gravou sexo sem consentimento!`,
      `👵 @${escolhido} já deu em cima de idoso no ônibus!`,
      `🍆 @${escolhido} já levou toco de travesti!`,
      `💋 @${escolhido} beija mal pra caralho!`,
      `👃 @${escolhido} tem coriza crônica!`,
      `🦠 @${escolhido} não lava a mão depois de cagar!`,
      `💩 @${escolhido} já cagou na calça no trânsito!`,
      `🍺 @${escolhido} já bebeu urina pensando que era cerveja!`,
      `🤮 @${escolhido} já vomitou na boca e engoliu!`,
      `👖 @${escolhido} usa cueca/calcinha furada!`,
      `💸 @${escolhido} já roubou dinheiro do velório!`,
      `📱 @${escolhido} tem nudes vazados na internet!`,
      `👀 @${escolhido} já foi pego se masturbando no trabalho!`,
      `💊 @${escolhido} já tomou Viagra sem precisar!`,
      `🍑 @${escolhido} já fez sexo no banheiro químico!`,
      `🚬 @${escolhido} fuma maconha com mato!`,
      `🤥 @${escolhido} mente a idade pra pegar menor!`,
      `👃 @${escolhido} tem fungo na unha do pé!`,
      `💦 @${escolhido} goza em 30 segundos!`,
      `📉 @${escolhido} já foi corno até do cachorro!`,
      `🍌 @${escolhido} já comeu comida de gato!`,
      `🚽 @${escolhido} não limpa a privada depois de cagar!`,
      `🐀 @${escolhido} já comeu miojo do lixo!`,
      `💸 @${escolhido} já vendeu celular roubado!`,
      `🤫 @${escolhido} já fez sexo com parente!`,
      `👵 @${escolhido} já traiu com a avó do amigo!`,
      `🍆 @${escolhido} tem pinto torto!`,
      `💋 @${escolhido} beija de língua demais!`,
      `👃 @${escolhido} tem bafo de onça morta!`,
      `🦠 @${escolhido} não toma banho depois do sexo!`,
      `💩 @${escolhido} já cagou na piscina!`,
      `🍺 @${escolhido} já bebeu álcool gel!`,
      `🤮 @${escolhido} já comeu catota!`,
      `👖 @${escolhido} usa meia suja vários dias!`,
      `💸 @${escolhido} já apostou até a cueca!`,
      `📱 @${escolhido} já criou fake pra se elogiar!`,
      `👀 @${escolhido} espia a mãe no banho!`,
      `💊 @${escolhido} já vendeu droga falsa!`,
      `🍑 @${escolhido} já fez menage com feio!`,
      `🚬 @${escolhido} fuma cigarro de palha!`,
      `🤥 @${escolhido} mente o signo pra dar sorte!`,
      `👃 @${escolhido} tem verruga no saco!`,
      `💦 @${escolhido} já gozou sem querer na amiga!`,
      `📉 @${escolhido} já foi traído pelo Uber!`,
      `🍌 @${escolhido} já comeu ração de cachorro!`,
      `🚽 @${escolhido} usa papel higiênico sujo!`,
      `🐀 @${escolhido} já comeu comida de rato!`,
      `💸 @${escolhido} já deve pensão alimentícia!`,
      `🤫 @${escolhido} já fez sexo no cemitério!`,
      `👵 @${escolhido} já pagou programa com idosa!`,
      `🍆 @${escolhido} já levou chá de banzo!`,
      `💋 @${escolhido} beija com os olhos abertos!`,
      `👃 @${escolhido} tem caspa que voa!`,
      `🦠 @${escolhido} não lava o umbigo!`,
      `💩 @${escolhido} já cagou no mato e limpou com folha!`,
      `🍺 @${escolhido} já bebeu álcool de limpar chão!`,
      `🤮 @${escolhido} já comeu meleca de nariz!`,
      `👖 @${escolhido} usa sutiã com aro quebrado!`,
      `💸 @${escolhido} já roubou doação de igreja!`,
      `📱 @${escolhido} já stalkeou até o 7º parente do ex!`,
      `👀 @${escolhido} já viu pornô da mãe!`,
      `💊 @${escolhido} já tomou remédio de cavalo!`,
      `🍑 @${escolhido} já fez sexo com animal!`,
      `🚬 @${escolhido} fuma crack escondido!`,
      `🤥 @${escolhido} mente o nome pra fugir da polícia!`,
      `👃 @${escolhido} tem ferida que não sara!`,
      `💦 @${escolhido} já ejaculou precoce!`,
      `📉 @${escolhido} já foi corno do padre!`,
      `🍌 @${escolhido} já comeu cola branca!`,
      `🚽 @${escolhido} não lava a mão depois de mijar!`,
      `🐀 @${escolhido} já comeu inseto de propósito!`,
      `💸 @${escolhido} já vendeu a alma por dinheiro!`,
      `🤫 @${escolhido} já fez sexo com o chefe!`,
      `👵 @${escolhido} já deu em cima do padre!`,
      `🍆 @${escolhido} já tomou bomba na academia!`,
      `💋 @${escolhido} beija com dente sujo!`,
      `👃 @${escolhido} tem chulé nuclear!`,
      `🦠 @${escolhido} não escova a língua!`,
      `💩 @${escolhido} já cagou na praia e enterrou!`,
      `🍺 @${escolhido} já bebeu perfume!`,
      `🤮 @${escolhido} já comeu unha do pé!`,
      `👖 @${escolhido} usa calcinha/cueca do avô!`,
      `💸 @${escolhido} já apostou a casa no jogo do bicho!`,
      `📱 @${escolhido} já criou fake de milionário!`,
      `👀 @${escolhido} espia os irmãos transando!`,
      `💊 @${escolhido} já vendeu placebo como droga!`,
      `🍑 @${escolhido} já fez sexo no telhado!`,
      `🚬 @${escolhido} fuma narguilé com água suja!`,
      `🤥 @${escolhido} mente a orientação sexual!`,
      `👃 @${escolhido} tem tumor no sovaco!`,
      `💦 @${escolhido} já gozou sem tirar a roupa!`,
      `📉 @${escolhido} já foi traído pelo irmão gêmeo!`,
      `🍌 @${escolhido} já comeu terra!`,
      `🚽 @${escolhido} usa jornal como papel higiênico!`,
      `🐀 @${escolhido} já comeu barata dormindo!`,
      `💸 @${escolhido} já roubou a mesinha de culto!`,
      `🤫 @${escolhido} já fez sexo no elevador!`,
      `👵 @${escolhido} já pagou sexo com mendigo!`,
      `🍆 @${escolhido} já usou enlarger!`,
      `💋 @${escolhido} beija com aparelho quebrado!`,
      `👃 @${escolhido} tem mau hálito matinal!`,
      `🦠 @${escolhido} não troca a escova de dente!`,
      `💩 @${escolhido} já cagou no vaso e transbordou!`,
      `🍺 @${escolhido} já bebeu água de vaso!`,
      `🤮 @${escolhido} já comeu cera de ouvido!`,
      `👖 @${escolhido} usa roupa íntima da irmã!`,
      `💸 @${escolhido} já deve pro agiota!`,
      `📱 @${escolhido} já hackeou o WhatsApp da mãe!`,
      `👀 @${escolhido} espia a empregada nua!`,
      `💊 @${escolhido} já tomou anabolizante!`,
      `🍑 @${escolhido} já fez sexo no carro do pai!`,
      `🚬 @${escolhido} fuma cigarro de manga!`,
      `🤥 @${escolhido} mente a nacionalidade!`,
      `👃 @${escolhido} tem fungo na virilha!`,
      `💦 @${escolhido} já gozou na comida do inimigo!`,
      `📉 @${escolhido} já foi corno do cachorro!`,
      `🍌 @${escolhido} já comeu sabão em pó!`,
      `🚽 @${escolhido} não fecha a porta pra cagar!`,
      `🐀 @${escolhido} já comeu formiga!`,
      `💸 @${escolhido} já vendeu curso falso!`,
      `🤫 @${escolhido} já fez sexo no cinema vazio!`,
      `👵 @${escolhido} já deu em cima do pastor!`,
      `🍆 @${escolhido} já usou gelo no pau!`,
      `💋 @${escolhido} beija com gengivite!`,
      `👃 @${escolhido} tem bafo de cebola!`,
      `🦠 @${escolhido} não lava o pau depois do sexo!`,
      `💩 @${escolhido} já cagou na calça na balada!`,
      `🍺 @${escolhido} já bebeu álcool 70!`,
      `🤮 @${escolhido} já comeu cola de papel!`,
      `👖 @${escolhido} usa cueca de pano!`,
      `💸 @${escolhido} já apostou o carro da mãe!`,
      `📱 @${escolhido} já clonou chip de celebridade!`,
      `👀 @${escolhido} espia os pais transando!`,
      `💊 @${escolhido} já vendeu chá de cogumelo!`,
      `🍑 @${escolhido} já fez sexo na piscina infantil!`,
      `🚬 @${escolhido} fuma palha de milho!`,
      `🤥 @${escolhido} mente a profissão!`,
      `👃 @${escolhido} tem verruga no cu!`,
      `💦 @${escolhido} já gozou no shampoo!`,
      `📉 @${escolhido} já foi traído pelo melhor amigo!`,
      `🍌 @${escolhido} já comeu cola de sapateiro!`,
      `🚽 @${escolhido} usa revista como papel higiênico!`,
      `🐀 @${escolhido} já comeu minhoca!`,
      `💸 @${escolhido} já roubou oferta de culto!`,
      `🤫 @${escolhido} já fez sexo no hospital!`,
      `👵 @${escolhido} já pagou programa com travesti!`,
      `🍆 @${escolhido} já usou bomba caseira!`,
      `💋 @${escolhido} beija com prótese dentária!`,
      `👃 @${escolhido} tem halitose terminal!`,
      `🦠 @${escolhido} não lava o cu!`,
      `💩 @${escolhido} já cagou no banheiro e não deu descarga!`,
      `🍺 @${escolhido} já bebeu gasolina!`,
      `🤮 @${escolhido} já comeu lombriga!`,
      `👖 @${escolhido} usa calcinha de renda furada!`,
      `💸 @${escolhido} já deve até a alma!`,
      `📱 @${escolhido} já invadiu rede social do ex!`,
      `👀 @${escolhido} espia a irmã no banho!`,
      `💊 @${escolhido} já tomou chá de ayahuasca!`,
      `🍑 @${escolhido} já fez sexo no banheiro do avião!`,
      `🚬 @${escolhido} fuma cigarro de cravo!`,
      `🤥 @${escolhido} mente a idade pra aposentar!`,
      `👃 @${escolhido} tem frieira no pé!`,
      `💦 @${escolhido} já gozou no ventilador!`,
      `📉 @${escolhido} já foi corno do gato!`,
      `🍌 @${escolhido} já comeu graxa!`,
      `🚽 @${escolhido} não lava a mão depois de coçar o cu!`,
      `🐀 @${escolhido} já comeu aranha!`,
      `💸 @${escolhido} já vendeu imóvel falso!`,
      `🤫 @${escolhido} já fez sexo na delegacia!`,
      `👵 @${escolhido} já deu em cima do médico!`,
      `🍆 @${escolhido} já usou vaselina como lubrificante!`,
      `💋 @${escolhido} beija com cárie!`,
      `👃 @${escolhido} tem bafo de alho!`,
      `🦠 @${escolhido} não troca a esponja de banho!`,
      `💩 @${escolhido} já cagou na rua e fingiu que não foi!`,
      `🍺 @${escolhido} já bebeu desinfetante!`,
      `🤮 @${escolhido} já comeu cola de madeira!`,
      `👖 @${escolhido} usa sutiã com bojo mofado!`,
      `💸 @${escolhido} já apostou a faculdade!`,
      `📱 @${escolhido} já criou fake de famoso!`,
      `👀 @${escolhido} espia a vizinha nua!`,
      `💊 @${escolhido} já vendeu gato por lebre!`,
      `🍑 @${escolhido} já fez sexo no carrinho de supermercado!`,
      `🚬 @${escolhido} fuma cigarro de palha de aço!`,
      `🤥 @${escolhido} mente o sobrenome!`,
      `👃 @${escolhido} tem câncer de pele!`,
      `💦 @${escolhido} já gozou no ar condicionado!`,
      `📉 @${escolhido} já foi traído pelo psicólogo!`,
      `🍌 @${escolhido} já comeu cola de isopor!`,
      `🚽 @${escolhido} usa mão como papel higiênico!`,
      `🐀 @${escolhido} já comeu lagartixa!`,
      `💸 @${escolhido} já roubou dízimo!`,
      `🤫 @${escolhido} já fez sexo no ônibus!`,
      `👵 @${escolhido} já pagou sexo com anão!`,
      `🍆 @${escolhido} já usou pasta de dente no pau!`,
      `💋 @${escolhido} beija com dentadura!`,
      `👃 @${escolhido} tem halitose crônica!`,
      `🦠 @${escolhido} não lava o sovaco!`,
      `💩 @${escolhido} já cagou no mato e sujou a mão!`,
      `🍺 @${escolhido} já bebeu querosene!`,
      `🤮 @${escolhido} já comeu cola de relógio!`,
      `👖 @${escolhido} usa cueca com marca de fezes!`,
      `💸 @${escolhido} já deve pro traficante!`,
      `📱 @${escolhido} já hackeou o email do chefe!`,
      `👀 @${escolhido} espia o irmão masturbando!`,
      `💊 @${escolhido} já tomou chá de LSD!`,
      `🍑 @${escolhido} já fez sexo no banheiro de rodoviária!`,
      `🚬 @${escolhido} fuma cigarro de maconha com tabaco!`,
    ];

    await sendText(fofocas[Math.floor(Math.random() * fofocas.length)], [escolhido + "@s.whatsapp.net"]);
  },
};